### ISSUE TITLE
Is the favicon correct?

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/tutorials.ubuntu.com#23]
Should we use the circle or friends, or is the current one on purpose? See image.

<img width="118" alt="screen shot 2017-01-12 at 13 23 34" src="https://cloud.githubusercontent.com/assets/223966/21887852/621ab3f8-d8ca-11e6-823c-8d3cd8e0ead0.png">

**Comment by magdalena-mirowicz** [comment]
no, but it's a duplication of existing bug so closing it
