### ISSUE TITLE
Cards need top border-radius

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/tutorials.ubuntu.com#24]
I think we need something like:

border-radius: 2px 2px 0 0

on the .header.horizontal div

See attached for what it looks like in Chrome. Top left is particularly bad.

<img width="335" alt="screen shot 2017-01-12 at 13 24 32" src="https://cloud.githubusercontent.com/assets/223966/21887899/a431beee-d8ca-11e6-93ef-72d5c8aa9fcd.png">

**Comment by grahambancroft** [comment]
Fixed on staging https://tutorials.staging.ubuntu.com/
