### ISSUE TITLE
Bottom buttons cover text

### ISSUE THREAD

**Issue by Lewciie** [ubuntudesign/tutorials.ubuntu.com#63]
At any of the tutorials, depending on the size of the window (but Im currently on laptop) the bottom button to go back covers part of the text.
![button](https://cloud.githubusercontent.com/assets/22214936/22029237/d25a8eb2-dcd1-11e6-82ce-354a0f09ca66.png)

**Comment by magdalena-mirowicz** [comment]
Hello, thank you for reporting. It's a duplicate of the existing bug 47 which has the High priority label assigned
