### ISSUE TITLE
Link to raise a bug on Tutorials points to codelabs

### ISSUE THREAD

**Issue by Lewciie** [ubuntudesign/tutorials.ubuntu.com#64]
The links on https://tutorials.ubuntu.com/ for **Did you find a mistake? Please file a bug.** points to https://github.com/ubuntu/codelabs/issues instead of here.

**Comment by magdalena-mirowicz** [comment]
thanks for spotting!

**Comment by magdalena-mirowicz** [comment]
@Lewciie it's fixed and live now
