### ISSUE TITLE
The project is missing a license

### ISSUE THREAD

**Issue by est31** [ubuntudesign/tutorials.ubuntu.com#80]
Hi! This project seems to be missing a license.

Its important to license a project for possible contributors and consumers alike. Also, its important to you because you don't appear to get the copyrights assigned, so making the conditions clear and explicit gives you stronger legal standing (I'm no lawyer though).

As its a collection of tutorials, I'd recommend the [CC-BY-SA 3.0](https://creativecommons.org/licenses/by-sa/3.0/) license.

**Comment by WillMoggridge** [comment]
Thanks for flagging this issue. We are currently reviewing our best options and will add the relevant information to the repo shortly.
