### ISSUE TITLE
Typo / Grammar on create-first-snap tutorial

### ISSUE THREAD

**Issue by dklickman** [ubuntudesign/tutorials.ubuntu.com#99]
Under the h2 header "Adding a part", 3rd paragraph, starting with "Two must-haves for every part are..."   Missing capital "S" for Snapcraft at the beginning of sentence unless it's intentional for command continuity :)

Link to page: 
https://tutorials.ubuntu.com/tutorial/create-first-snap#2

I look forward to the snap's development, thanks for yalls time!

**Comment by WillMoggridge** [comment]
Thanks! I have proposed it to the source document for the tutorial team to look at. :)

**Comment by WillMoggridge** [comment]
That change has been accepted and it will be updated on the site on our next tutorials build.
